import type { Detection } from "../state/app-types";

type Props = { detections: ReadonlyArray<Detection>; selectedDetectionId: number | null; onSelectDetection: (id: number) => void; onViewSonar: () => void };
export default function DetectionMapPage({ detections, selectedDetectionId, onSelectDetection, onViewSonar }: Props) {
  const selected = detections.find((item) => item.id === selectedDetectionId);
  const located = detections.filter((item) => item.latitudeValue !== null && item.latitudeValue !== undefined && item.longitudeValue !== null && item.longitudeValue !== undefined);
  const minLat = Math.min(...located.map((item) => item.latitudeValue!));
  const maxLat = Math.max(...located.map((item) => item.latitudeValue!));
  const minLon = Math.min(...located.map((item) => item.longitudeValue!));
  const maxLon = Math.max(...located.map((item) => item.longitudeValue!));
  const position = (value: number, minimum: number, maximum: number) => maximum === minimum ? 50 : 8 + ((value - minimum) / (maximum - minimum)) * 84;
  const formatCoordinate = (value: number, positive: string, negative: string) => `${Math.abs(value).toFixed(4)}° ${value >= 0 ? positive : negative}`;
  return <div className="page-section"><div className="page-intro"><div><span className="eyebrow">{located.length} LOCATED · UPLOADED SCAN</span><h2>Detection coordinate plot</h2><p>Markers use coordinates returned by the analysis API. No coordinates are inferred from pixels.</p></div><span className="live-indicator">{located.some((item) => item.geolocationType === "Real") ? "REAL LOCATION DATA" : located.some((item) => item.geolocationType === "Simulated") ? "SIMULATED COORDINATES" : "LOCATION STATUS FROM API"}</span></div>
    <div className="map-layout"><section className="marine-map" aria-label="Analysis coordinate plot"><div className="map-coordinate map-nw">{located.length ? `Max latitude · ${formatCoordinate(maxLat, "N", "S")}` : "NO COORDINATES"}</div><div className="map-coordinate map-se">{located.length ? `Min latitude · ${formatCoordinate(minLat, "N", "S")} · Max longitude · ${formatCoordinate(maxLon, "E", "W")}` : "FROM API RESPONSE"}</div><svg viewBox="0 0 1000 700" preserveAspectRatio="none" aria-hidden="true"><path d="M110 590 Q160 120 260 110 Q380 100 420 600 M270 610 Q330 70 480 80 Q620 85 650 610 M450 620 Q500 80 690 115 Q820 135 860 620 M615 610 Q690 90 920 180"/><path d="M40 510 Q380 425 960 360 M40 310 Q440 280 940 220" className="coverage-track-secondary"/></svg>
      {located.map((detection) => { const left = position(detection.longitudeValue!, minLon, maxLon); const top = 100 - position(detection.latitudeValue!, minLat, maxLat); return <button key={detection.id} className={`map-marker priority-${detection.priority}${selectedDetectionId === detection.id ? " is-selected" : ""}`} style={{ left: `${left}%`, top: `${top}%` }} aria-label={`Detection ${detection.id}, ${detection.type}, ${detection.priority} priority`} onClick={() => onSelectDetection(detection.id)}><span>{detection.id}</span></button>; })}
      {located.length === 0 && <div className="map-empty-state"><strong>No coordinates returned</strong><span>The backend did not provide verified image navigation metadata.</span></div>}
      <div className="map-legend">{(["high", "medium", "low", "uncertain"] as const).map((priority) => <span key={priority}><i className={`priority-${priority}`} />{priority}</span>)}</div>
    </section><aside className="panel map-detail"><span className="eyebrow">SELECTED MARKER</span>{selected ? <><h3>Detection #{selected.id}</h3><strong>{selected.type}</strong><p>Dataset: {selected.sourceDataset ?? "Unavailable"}<br />Confidence: {selected.confidence === null ? "Unavailable" : `${selected.confidence}%`}<br />Priority: {selected.priority}<br />Status: {selected.status.replaceAll("-", " ")}</p><p className="mono">{selected.latitude}<br />{selected.longitude}</p><button className="primary-button" onClick={onViewSonar}>View sonar ↓</button></> : <p className="muted">Choose a located marker to see its details.</p>}<small className="demo-note">Coordinates are displayed only when supplied by the API.</small></aside></div></div>;
}
