"""Train and optionally evaluate a separate one-class synthetic ghost-net model."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", required=True, help="data.yaml from engine10_ghostnet.generate")
    parser.add_argument("--model", default="yolov8n.pt")
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--device", default=None)
    parser.add_argument("--project", default="runs/engine10_ghostnet")
    parser.add_argument("--name", default="synthetic-only")
    parser.add_argument("--evaluate-synthetic-test", action="store_true")
    args = parser.parse_args()
    if args.epochs < 1 or args.imgsz < 1 or args.batch < 1:
        parser.error("epochs, imgsz, and batch must be positive")
    data = Path(args.data).expanduser().resolve()
    if not data.is_file():
        parser.error(f"dataset yaml not found: {data}")
    report_path=data.parent/"generation_report.json"
    if not report_path.is_file():
        parser.error("Engine 10 accepts only a dataset generated by engine10_ghostnet.generate")
    generation_report=json.loads(report_path.read_text(encoding="utf-8"))
    if generation_report.get("status") != "SYNTHETIC_EXPERIMENT_ONLY":
        parser.error("dataset is not marked as a separate synthetic-only experiment")
    if generation_report.get("background_count", 0) < 3:
        parser.error("at least three independent backgrounds are required for grouped train/validation/test splits")
    if args.evaluate_synthetic_test and not generation_report.get("synthetic_test_available"):
        parser.error("independent background groups are insufficient for synthetic-test evaluation")
    if args.evaluate_synthetic_test:
        yaml_text=data.read_text(encoding="utf-8")
        test_match=re.search(r"^test:\s*(.+?)\s*$",yaml_text,re.MULTILINE)
        test_folder=(data.parent/test_match.group(1)) if test_match else None
        if test_folder is None or not test_folder.is_dir() or not any(test_folder.iterdir()):
            parser.error("synthetic_test image split is missing or empty")
    try:
        from ultralytics import YOLO
    except ImportError as exc:
        raise SystemExit("Install requirements-engine4.txt before training") from exc
    model = YOLO(args.model)
    options = {"data": str(data), "epochs": args.epochs, "imgsz": args.imgsz,
               "batch": args.batch, "project": args.project, "name": args.name}
    if args.device is not None:
        options["device"] = args.device
    model.train(**options)
    if not args.evaluate_synthetic_test:
        print("Training complete. No metrics were computed; use --evaluate-synthetic-test to score only synthetic held-out backgrounds.")
        return
    save_dir = Path(model.trainer.save_dir)
    best = save_dir / "weights" / "best.pt"
    evaluator = YOLO(str(best))
    test_metrics = evaluator.val(data=str(data), split="test", imgsz=args.imgsz,
                                 device=args.device or "cpu", plots=True)
    report = {"status": "SYNTHETIC_ONLY_NOT_FIELD_VALIDATION", "model": str(best),
              "evaluation_split": "synthetic_test", "metrics": dict(test_metrics.results_dict),
              "claim_boundary": "These metrics measure only the synthetic held-out set and must not be presented as real-world ghost-net accuracy."}
    out = save_dir / "synthetic_only_metrics.json"
    out.write_text(json.dumps(report, indent=2, default=float), encoding="utf-8")
    print(json.dumps(report, indent=2, default=float))


if __name__ == "__main__":
    main()
